### ISSUE TITLE
Performance?

### ISSUE THREAD

**Issue by keehun** [Blue-Rocket/BRFullTextSearch#10]
Hi,

I'm looking to use BRFullTextSearch for my upcoming musician's dictionary app. What's the performance like? The HTML table of all the entries are about 27MB. I've yet to clean/import/etc into CoreData, but it would be nice to have some idea if BRFullTextSearch will be able to handle the amount of entries. I particularly liked seeing [some numbers/graphs here](https://github.com/matehat/MHTextSearch).

Thanks for a wonderful library! Look forward to investigating a bit further.

keehun

**Comment by msqr** [comment]
Hi keehun,

I don't have any nice charts like those you refer to, sorry. I can say that I've used BRFullTextSearch in many production iOS apps, going back as far as the iPad 1, and performance has not been an issue. 27MB of HTML does not sound like it would present any problems to me. Even if indexing took a bit of time, searches should remain pretty fast.

That being said, BRFullTextSearch is a pretty thin wrapper around [CLucene](http://clucene.sourceforge.net/) and the performance characteristics of this should pretty much match that.

**Comment by keehun** [comment]
Hi msqr,

Thank you for that response! I've read a lot of good things about CLucene, and so I'll probably go ahead and explore BRFullTextSearch first.

If I pre-indexed a CoreData database and included that in the binary [as outlined here](https://www.objc.io/issues/4-core-data/importing-large-data-sets-into-core-data/), the user shouldn't have to wait at all, right?

Thanks
keehun

**Comment by msqr** [comment]
Sure, you could generate the Lucene database and then include that in your application. It will be a directory with a set of files. In fact you could even generate the Lucene database with Java Lucene, you would just need to use version 2.3.2 to match what CLucene expects.

**Comment by keehun** [comment]
Sorry for my very novice questions, but based on your answer, I infer that:
- If I [generated the Lucene database](http://www.avajava.com/tutorials/lessons/how-do-i-use-lucene-to-index-and-search-text-files.html?page=1) (which I've now gathered is a multi-file-based system) and imported/supplied it correctly to `CLuceneSearchService`'s `initWithIndexPath:` initializer, then it would bypass all of the initial indexing (i.e. as outlined in the batch processing part of the README).
- This would then have nothing to do with CoreData

Is this correct?

**Comment by msqr** [comment]
Yes, that should work (again, you must create a version 2.3.2 database), and it would have nothing to do with Core Data.

If you need to associate index documents (i.e. search results) to Core Data entities, you'd need some sort of identifier associated with both the documents and the entities, so given a search result you could load the appropriate entity from Core Data.

**Comment by keehun** [comment]
> Yes, that should work (again, you must create a version 2.3.2 database), and it would have nothing to do with Core Data.

I just downloaded the 2.3.2 jar and am attempting to create my first index!

> If you need to associate index documents (i.e. search results) to Core Data entities, you'd need some sort of identifier associated with both the documents and the entities, so given a search result you could load the appropriate entity from Core Data.

This won't be necessary at the moment, but that makes perfect sense. Is there a way to store metadata in the Lucene index? Or would I just have metadata within the files that are indexed? Say I have a lot of words to be indexed, and I want Lucene to know which language they're in. Perhaps I can make the first line of every word-file the language code? (i.e. en-us, de, fr, etc)

Again, thank you for being so helpful, and sorry if this is in the documentation somewhere--I should go look.

**Comment by msqr** [comment]
No worries. An index document in Lucene is like a dictionary or key/value store. You index values for associated keys. So any metadata you want to associate with the document you simply add as additional keys to that document. Conceptually you might have an index document that resembles:

``` json
{
  "lang" : "en-us",
  "title" : "Some Title",
  "text" : "Some paragraphs of text here."
}
```

There are many helpful tutorials on Lucene around the web as it is a popular open source search engine!

**Comment by keehun** [comment]
Ok. After reading some Lucene-based articles/stack-overflow, I think I'm starting to finally understand this. At first I wondered why my full paths of the files were showing up in the generated index files. Then I realized that the Java code I was using was the one telling Lucene to store that data.

I get it conceptually now--I'm making a Lucene Document object and I can feed it all sorts of data. I've been reading the file and injecting that whole-sale into one of the fields, but I now realize I can parse that definition file myself and put different parts of that definition file into different fields in the Lucene Document!

Thank you!

**Comment by msqr** [comment]
You're welcome. I'll close out this ticket then. Feel free to open new ones if you run into issues.
