### ISSUE TITLE
sorting by multiple fields

### ISSUE THREAD

**Issue by jpmhouston** [Blue-Rocket/BRFullTextSearch#11]
I don't know much about this Pod, or `CLucene`, but I'm faced with either adding multi-field sorting or abandoning this for another solution. Before I waste too much time, can someone say whether this would this work?

In `CLuceneSearchService` changing the `sortBy` argument in the internal `searchWithQuery:sortBy:sortType:ascending:` from an `NSString` to an `NSArray`, and its implementation like:

``` Objective-C++
- (id<BRSearchResults>)searchWithQuery:(std::auto_ptr<Query>)query
                              sortBy:(NSArray *)sortFieldNames
                            sortType:(BRSearchSortType)sortType
                           ascending:(BOOL)ascending {
    std::tr1::shared_ptr<Searcher> s = [self searcher];
    if ( sortFieldNames != nil && sortFieldNames.count > 0 ) {
        SortField *sortFields[sortFieldNames.count + 2];
        int idx = 0;
        for (NSString *sortFieldName in sortFieldNames) {
            SortField *sortField = new SortField([sortFieldName asCLuceneString], (sortType == BRSearchSortTypeInteger
                                                                                   ? SortField::INT
                                                                                   : SortField::STRING), !ascending);
            sortFields[idx++];
        }
        SortField *docFieldSort = ascending ? SortField::FIELD_DOC() : new SortField(NULL, SortField::DOC, true);
        sortFields[idx++] = docFieldSort; // ensures we have consistent results if a sort field has duplicate values
        sortFields[idx] = NULL; // requires NULL last element
        std::auto_ptr<Sort> sort(new Sort(sortFields)); // assumes ownership of each SortField
        std::auto_ptr<Hits> hits(s->search(query.get(), sort.get()));
        return [[CLuceneSearchResults alloc] initWithHits:hits sort:sort query:query searcher:s];
    }
    std::auto_ptr<Hits> hits(s->search(query.get()));
    std::auto_ptr<Sort> sort;
    return [[CLuceneSearchResults alloc] initWithHits:hits sort:sort query:query searcher:s];
}
```

Then making the obvious changes to `search:sortBy:..` and `searchWithPredicate:sortBy:...` to call it with `... sortBy:@[sortFieldName]...`, and making additional methods `search:sortByMultiple:..` and `searchWithPredicate:sortByMultiple:...`.

I can do a pull request if this works.

**Comment by msqr** [comment]
Thanks for your interest in the project. As you discovered when looking at the CLucene API, it does support sorting on multiple fields. Updating the BRFTS API to support this has been an outstanding task in the back of my mind for some time, actually. To that end, check out the [multi-sort](/Blue-Rocket/BRFullTextSearch/tree/feature/multi-sort) branch, where I've added two new methods:

``` objc
// parsed query with an array of sort descriptors
- (id <BRSearchResults> )search:(NSString *)query 
            withSortDescriptors:(nullable NSArray<id<BRSortDescriptor>> *)sorts;

// predicate query with an array of sort descriptors
- (id <BRSearchResults> )searchWithPredicate:(NSPredicate *)predicate 
                             sortDescriptors:(nullable NSArray<id<BRSortDescriptor>> *)sorts;
```

The [BRSimpleSortDescriptor](/Blue-Rocket/BRFullTextSearch/blob/feature/multi-sort/BRFullTextSearch/BRSimpleSortDescriptor.h) provides a basic implementation of `BRSortDescriptor` for you, and there is a [unit test](/Blue-Rocket/BRFullTextSearch/blob/feature/multi-sort/BRFullTextSearchTests/CLuceneSearchServiceTests.mm#L428) that shows this working. **Also note** [Lucene has limitations](/Blue-Rocket/BRFullTextSearch/blob/feature/multi-sort/BRFullTextSearch/CLuceneSearchService.h#L34) on the fields you can sort on.

If you'd like to try out this branch with your project, let me know how it goes for you and if all is well I can merge this into the next release.

**Comment by jpmhouston** [comment]
Thanks, I didn't see that branch. I'll investigate whether we can work within Lucene's limitations you mentioned, and if so, then indeed I'll be exercising this branch. Would you like me to email my feedback to you directly @msqr, or post it in this thread?

**Comment by msqr** [comment]
Great! Go ahead and post any feedback on this thread if you can.

**Comment by msqr** [comment]
Hi @jpmhouston did you have any luck using the _multi-sort_ branch? I am likely to merge this in for the next release, but would be interested to hear if you tried it out.

**Comment by jpmhouston** [comment]
Didn't get a chance yet, and now the project is being shelved & I'm moving on so it looks like I won't ever. :^(

**Comment by msqr** [comment]
Ah well, I have a few of unit tests in there at least, so I'll merge it in. Thanks!
