### ISSUE TITLE
Scoring & Exact Matches

### ISSUE THREAD

**Issue by keehun** [Blue-Rocket/BRFullTextSearch#16]
Sometimes, exact matches don't show up as the first result. Is there a way to configure BRFullTextSearch/Lucene to make sure that exact matches show up as the first result? Sometimes it's the first one and sometimes not.

**Comment by msqr** [comment]
Can you provide an example test case? By default Lucene is sorting by relevance, and "exact match" can be different from what you expect, for example when stemming is enabled. Different document matches might end up with the same score.

You might also find it useful to use a tool like [Luke](http://www.getopt.org/luke/) (you can get an [old version](http://www.getopt.org/luke/luke-0.8.1/lukeall-0.8.1.jar) that uses a 2.3.x version of Lucene to be more similar to CLucene) to debug your queries and see how documents are scored. You just have to be careful to use the same analyzer for your searches as then one you generated your index with.

**Comment by msqr** [comment]
Closing from lack of discussion.
