### ISSUE TITLE
"No segments* file found in" directory

### ISSUE THREAD

**Issue by hudaniel** [Blue-Rocket/BRFullTextSearch#18]
I keep running into this issue. I copied the example usage exactly and ran into this exception from CLucene

```
_CLTHROWA(CL_ERR_IO, (string("No segments* file found in ") + directory->toString()).c_str());
```

Is there some permission I'm not doing right? I even tried:

```
NSString *tmpDir = NSTemporaryDirectory();
service = [[CLuceneSearchService alloc] initWithIndexPath:tmpDir];
```

Instead of the default one in the example usage

**Comment by msqr** [comment]
Can you check the full path of the directory getting passed to CLucene, and then see if you don't have permission to create that directory, or files in that directory?

**Comment by hudaniel** [comment]
So the default one is:

```
../CoreSimulator/Devices/23D06471-9888-4032-8BFF-00D9479D2D71/data/Containers/Data/Application/BE24CC3C-2132-4ECF-A25A-2B2DC913B490/Library/Application Support/MyApp/lucene.idx
```

Do I have to do anything to enable permissions to create this directory? Also, the sample projects run perfectly fine (after updating the Podfile). I checked that the Sample Projects produce a directory that is similar.

**Comment by hudaniel** [comment]
I confirmed that I have the right permissions to edit the `lucene.idx` directory.

**Comment by msqr** [comment]
That exception is thrown when the Lucene index has not been created yet. Are you seeing that exception bubble all the way up to your app, or do you have a C++ exception break point set in the debugger?

**Comment by hudaniel** [comment]
Ah it's caused by the All Exceptions break point firing in Xcode even though this exception could be ignored. I guess I should throw this exception out. Thanks for looking into this for me.

**Comment by msqr** [comment]
CLucene throws quite a few C++ exceptions during the normal flow of operation, so yes many of them can be ignored. Glad I could help!
