### ISSUE TITLE
Index corruption

### ISSUE THREAD

**Issue by dsanghan** [Blue-Rocket/BRFullTextSearch#19]
Is there an easy way to detect if the index file is corrupted? We're seeing a very small proportion of our users have a power/disk failure and on restarting, the index file becomes unreadable and they can't get back into the app since the app crashes on 

`_searchService = [[CLuceneSearchService alloc] initWithIndexPath:[self searchServicePath]];`

**Comment by msqr** [comment]
Is the crash caused by an uncaught exception, by chance? I was imagining if so, the exception could be caught, and then you could choose to delete the index and re-create it.

**Comment by dsanghan** [comment]
I was already handling the exception, but I haven't seen it happen in the last month so I'll just close it out. Thanks!
