### ISSUE TITLE
Crash with custom analyzer and empty stop word filter

### ISSUE THREAD

**Issue by gfzabarino** [Blue-Rocket/BRFullTextSearch#20]
Hi, first of all, thanks for making this awesome project! It's exactly what I needed.

In order to adjust it to my app's needs, I had to make a similar implementation of the default analyzer, and use a `KeywordTokenizer` instead of a `StandardTokenizer`, because I have some codes that have leading numbers (1 digit) and those numbers were being discarded when indexing. `KeywordTokenizer` makes it work.

However, when using the same approach as the standard analyzer, there seems to be a crash on the `StopFilter`, when the stop work set is empty. It seems that the first index gets filled with invalid data (even though is set to NULL by code, like the standard analyzer does), therefore tries to compare pointers' data, and it crashes because of an invalid memory address.

Right now, I'm making it work by just never add the `StopFilter`, I'm not using that anyways. But I'm afraid it crashes on other parts later. So far it didn't, but you never know...

Did that ever happened to you? Did you have to use any special C++ compiler flag to make sure that doesn't happen? Thanks!

**Comment by msqr** [comment]
I haven't experienced the same issue you're facing, unfortunately. I can say from my experience of working with the CLucene code base is that you must investigate quite carefully the pointer ownership semantics of every object you instantiate. Some CLucene APIs take ownership of passed in pointers, some do not. That may not be what you're facing, of course!

**Comment by msqr** [comment]
Closing from lack of discussion.

**Comment by gfzabarino** [comment]
Just to give some closure to this, I haven't touched my code since I created this issue, that is, I never added the `StopFilter` back. By doing that I never experienced another crash. Unfortunately I can't tell if the issue is still happening when using it, nor have a fix for it.

**Comment by msqr** [comment]
Thanks for the feedback.
