### ISSUE TITLE
Match in multiple properties

### ISSUE THREAD

**Issue by rabehssera** [Blue-Rocket/BRFullTextSearch#25]
Hello

Is it possible to do a search in multiple properties at once ? For example, if my Class has a Title and a Description, can I search in the title and the description in one query ?

And is it possible to "filter" my results to "all the words were found" ?
And can I define a list of words that I don't want to be searched (like "the")

Thanks

**Comment by msqr** [comment]
Yes you can achieve what you outline. The underlying search engine is [CLucene](http://clucene.sourceforge.net/), and if you use the `NSString` based query methods on `BRSearchService` ([like this](https://github.com/Blue-Rocket/BRFullTextSearch/blob/046a53ef34d4021916b7cc770c0b4f5d3511581d/BRFullTextSearch/BRSearchService.h#L271-L280)) the syntax is similar to the [Java Lucene 2.x query parser syntax](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html).

Back to your example, if you index _title_ and _description_ fields `t` and `d` then queries like

```
t:foo d:foo
```

will search both title and description for `foo`, matching either.  A query like

```
t:foo AND d:bar
```

would find only matches where the title contains `foo` **and** the description contains `bar`.
