### ISSUE TITLE
Fails to Build under Xcode's New Build System

### ISSUE THREAD

**Issue by mikecsh** [Blue-Rocket/BRFullTextSearch#27]
I think this is worth noting despite the fact it's based on a beta version of Xcode.

The BRFullTextSearchMacOS framework fails to build under Xcode 9.2 beta's experimental new build system. It complains that the nodes _FastCharStreamer.h, Scorer.h, and libstemmer.h are produced by multiple commands.

This is reproducible by downloading the latest version of master, opening it in Xcode 9.2b, switching the target to BRFullTextSearchMacOS, changing to the new build system using the File->Workspace Settings menu and attempting to build.

**Comment by msqr** [comment]
Hey @mikecsh sorry about the radio silence on this issue. I have not been involved with maintaining this project for a while now, and I'm afraid I don't have any solutions to offer. Perhaps someone else out there could say if there is a work-around?

**Comment by mikecsh** [comment]
Hi @msqr, thanks for your comment! No worries, I wasn't able to find a solution to this so have switched to an alternative for FTS. Thanks for all your work on BRFTS in the past though, it was a very nice solution!

**Comment by msqr** [comment]
Ah, ok! Sorry I couldn't be more helpful. I'll close this issue then.
