### ISSUE TITLE
Cannot compile with XCode 10.1 due to libstdc++ deprecation.

### ISSUE THREAD

**Issue by andrewhoyer** [Blue-Rocket/BRFullTextSearch#28]
On moving to XCode 10.1 from version 9, this can no longer be compiled as part of a project. Apparently, the libstdc++ library isn't being included as of this release.

Is there a chance of BRFullTextSearch getting an update to bring it to where it is compatible with XCode 10.1?

**Comment by msqr** [comment]
Have you tried the [2.0.0-beta1](/Blue-Rocket/BRFullTextSearch/releases/tag/2.0.0-beta1) release? That release switched to `libc++` and might compile for you.

**Comment by msqr** [comment]
Closing as abandoned.
