### ISSUE TITLE
Integration via CocoaPods

### ISSUE THREAD

**Issue by voluntas88-xsolve** [Blue-Rocket/BRFullTextSearch#4]
Hi! If there is using command 'use_frameworks!' in Podfile, BRFullTextSearch will not compile and huge amount of errors will appear (at least I faced such case). Removing that command from Podfile fixed me the issue. Maybe it will be good idea put this info to readme.
Thanks.

**Comment by msqr** [comment]
Thanks for the note. I have updated the README as suggested. I am not able to investigate making the Pod usable as a dynamic framework at the moment, so welcome any pull requests that can address this issue.
