### ISSUE TITLE
Snippets

### ISSUE THREAD

**Issue by frankai** [Blue-Rocket/BRFullTextSearch#5]
Hello!

Congratulations, this is an excellent iOS port of CLucene, we are using it in our projects.

Any clue about how do we extract small snippets of texts from each match?

Thanks in advance,

Frankai

**Comment by msqr** [comment]
Hello Frankai,

Thank you, I'm glad you find the package useful. Can you be more specific about what you're trying to achieve? As long as you are using the `BRIndexableStorageTypeStore` flag for your indexed data, the full original text is available to you in each match.

-- m@

**Comment by frankai** [comment]
Hi!

Yes, we have the full original text in each match, but I just want to present the results with an extract of the words around each match (ie: Google results, a text fragment containing your search terms in bold). 

I can process each result and search again the full original text on my own, but sometimes the user search query is not the same that CLucene uses internally, for example, if we use StemmedPrefixSearches= YES.

Could we get the CLucene internal search terms that fired each hit in the results?

Thanks!

Frankai

**Comment by msqr** [comment]
Ah, yes I thought that might be what you were trying to achieve. Lucene calls that "highlighting" and it does support that, but the BRFullTextSearch API itself does not. This has long been a desired feature, and there is even [a branch](https://github.com/Blue-Rocket/BRFullTextSearch/tree/feature/highlighter) that was created to work on it, but it hasn't really got off the ground yet.

**Comment by frankai** [comment]
Ok, thanks, I'll try it.
