### ISSUE TITLE
What are the possible values of indexObjectType?

### ISSUE THREAD

**Issue by mrtj** [Blue-Rocket/BRFullTextSearch#7]
Hi I am trying to implement a search feature with your search engine, but I do not really understand what I supposed to return as indexObjectType in my custom indexable object implementing BRSearchObjectType protocol. I saw that the default BRSimpleIndexable implementation returns a question mark ('?') and in your Core Data example the StickyNote implementation returns an 'n' character. Could you add some reference to the documentation wether these characters have some special meaning or they are simple used to differentiate the object types, so I can give the arbitrary values?

**Comment by msqr** [comment]
They are only used to differentiate object types, and can have arbitrary values defined by the application using BRFullTextSearch (`BRSearchObjectType` is defined as a `char`). [BRIndexable](http://cocoadocs.org/docsets/BRFullTextSearch/1.0.10/Protocols/BRIndexable.html) does talk about how index documents are uniquely identified by the combination of their object type and their identifier. Some applications don't need to differentiate and can use a single object type, but often it can be useful.

I can add more explicit documentation as you suggest, about how they `BRSearchObjectType` are arbitrary, application-defined values.

**Comment by mrtj** [comment]
Thank you, now it is clear!
