### ISSUE TITLE
[Request] Mac OS Targets

### ISSUE THREAD

**Issue by phildow** [Blue-Rocket/BRFullTextSearch#8]
First of all thank you for providing an Objective-C wrapper around Lucene! This is excellent.

I'd like to use the static framework in a project that targets both Mac OS and iOS. Right now it's building for iOS only. I suspect there is nothing in the code that is iOS specific and that building for Mac OS is a matter of creating a new target with different build settings while ensuring everything else is the same.

I understand that you may not have a Mac OS use case, so I'm going to try this and may make a pull request, but I wanted to mention it because you might be able to add a Mac OS target more quickly, being familiar with the code already.

**Comment by msqr** [comment]
I'm glad you find it useful! 

I don't have the ability to try to get an OS X build configured at the moment, so if you can get a PR together that would be great. I remember seeing [a fork some time ago](https://github.com/ovlach/BRFullTextSearch/commit/983fec3aef78f8c2955cf687873ffd2423952493) with comments about supporting OS X. It looks like the only change made there was to the Podspec, however, so it might not be very helpful.

**Comment by phildow** [comment]
Ok, I think I'm getting close. Xcode is kicking me in the butt though. I've got a Mac OS framework build but I'm having trouble getting the header files to all copy into the right place. I notice you're using a shell script to do that for the iOS build, so I'm going to try to duplicate that. I then get what I think are header search path problems when I use the Mac OS framework in a Mac OS sample application that I've also added.

However, I know it's otherwise working because, after manually copying the headers to the right place, I can copy the built framework into a separate Xcode project and index and search!

**Comment by msqr** [comment]
That's great! I'll have a look at the PR you've created as soon as I can.

**Comment by mikecsh** [comment]
Perfect timing - I came to say the same thing! This would be extremely useful on OS X as well.

**Comment by phildow** [comment]
@mikecsh I got a pull request in. Have a look at the macos-framework branch on https://github.com/phildow/BRFullTextSearch and the sample project at https://github.com/phildow/brfulltextsearch-macos-swift-example

**Comment by mikecsh** [comment]
Thanks very much @phildow , will do!

**Comment by msqr** [comment]
Hi @mikecsh it would be very helpful if you could test out @phildow's branch and provide any feedback on using it.

**Comment by mikecsh** [comment]
@msqr I'm having a look at it now and will report back here with how I get on

**Comment by phildow** [comment]
@mikecsh The only thing to note is that you want to Archive the application to produce the release build, instead of build it, which produces the debug build. Of course you could edit the scheme to produce the release build as well.

If you figure out how to get a sample application using the Mac OS framework into the workspace that'd be great too. I couldn't get Xcode to recognize the framework's headers.

**Comment by msqr** [comment]
Hi @mikecsh did you have any luck with the Mac OS target from @phildow's branch?

**Comment by mikecsh** [comment]
@msqr unfortunately I got sidetracked on this. I still plan to look at it but it probably won't be for a couple of weeks..

**Comment by msqr** [comment]
No worries @mikecsh, thanks for the update.

**Comment by dsanghan** [comment]
@phildow Fork worked great for my OSX project. Much thanks!

**Comment by msqr** [comment]
Thanks @dsanghan. I've started merging this PR, along with setting up OS X Cocoapod support. I'm working on an OS X sample project as well. This work is currently in the [feature/osx](/Blue-Rocket/BRFullTextSearch/tree/feature/osx) branch.

**Comment by msqr** [comment]
This work has been merged into the [develop](/Blue-Rocket/BRFullTextSearch/tree/develop) branch and will be included in the 1.1.1 release.

**Comment by mikecsh** [comment]
A very late and probably now unnecessary response - but just to say this is working flawlessly in my macOS target now - thank you!
